name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Proj

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

  steps:
    - name: Build app on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcys8uN/5ROCKAUw2pa3Umv4cNT8nM9HNLNTq8QlYNtHBwXrnUP+1XBilYNoQkzAJpaUw1zMjqtPRkBl4E7ozmmAKu/eGEzPGGn9HvTgVc8ZZgczwJWvqT/f0SU5PnKORipGLUvnMrieSPhq1N7+HxlvK0bUzYjEOn/wjujS5uSDaGqchcdu/pEK3XTTa1/pwwJXB5kH1gJ9Rv+W/z4CpJ3izfTD4zLuzJs+NR/2rZCzCZ0RVEYMmbiYa1tlFd5rDbSIKWEambELDTtoH9edPl8Ywtky2CUq29xq4fOoara9fmG6Sbk2yyi6IHDC9OttS6ZmKRHDlUsbfPrqnCdq0IhSnoP1OQvzieg6CkHwL71NxmgbnRBKxTQJxn6QfEKZRpikHF5mNOoI2Zagv9XoSTdkk7F3h0OPAdfuOFpMHkycaGsH+nTQ4Ut7Q+Yndnxsqbc6H7cCX5gc76Jb/9+J/3Go00M5iQt3LnaMeVtuwG6vdOP8SaSDgbFYZnNdv+4ja+bV04kuBsTemVPhG+hOP6HaX/3cJHI7HIX799jpi03ybVzMp+E7djaX+Cs3JQBkL37Dq24rcSTT6yVKGz/oWo/8guqbYpksT3SYTBcm7RwYuJK02eHSOJbRS2pHMb5fRXNxxNc0UWRXZKII+JQOHtPBCYgXBuwDsCSc3yvt9U+Q== Praktikan6"
          echo "Cek folder project";
          [ ! -d "${HOME}/senpro/534368/modul02/senpro-github-action/" ] &&
          {
            echo "Repository belum di-clone. Cloning...";
            mkdir -p ~/senpro/534368/modul02;
            cd ~/senpro/534368/modul02;
            git clone https://github.com/theoimmanuel/senpro-github-action.git;
            cd ~/senpro/534368/modul02/senpro-github-action;
            echo "Install Package dan Build Project";
            npm install;
            npm run build;
          } ||
          {
            echo "Repository sudah ada. Building...";
            cd ~/senpro/534368/modul02/senpro-github-action;
            git restore .;
            git pull origin main;
            echo "Install Package dan Build Project";
            npm install;
            npm run build;
          }